version: '3'
services:

    pgsql:
        image: postgres:14.7
        volumes:
            - ./db:/var/lib/postgresql/data
            # - ./postgres-initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
        ports:
            - "5432:5432"
        networks:
            - dev-net
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
            
    adminer:
        image: adminer
        restart: always
        networks:
            - dev-net
        ports:
            - 8080:8080

    redis:
        image: redis:latest
        user: redis
        networks:
            - dev-net
        ports:
            - "0.0.0.0:6379:6379"

    rabbitmq:
        container_name: rabbitmq
        image: rabbitmq:latest
        hostname: rabbitmq
        ports:
            - 5672:5672
            - 15672:15672
        networks:
            - dev-net
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=admin
            - RABBITMQ_DEFAULT_VHOST=/

networks:
    dev-net:
        driver: bridge